"""init

Revision ID: 94611849b1b2
Revises: 
Create Date: 2024-05-03 11:59:29.407577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from db_connector.types import TextJson

# revision identifiers, used by Alembic.
revision: str = '94611849b1b2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('services',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('webhook', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('settings',
                    sa.Column('key', sa.String(), nullable=False),
                    sa.Column('value', TextJson(), nullable=True),
                    sa.PrimaryKeyConstraint('key')
                    )
    op.create_table('users',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('tg_id', sa.Integer(), nullable=False),
                    sa.Column('external_id', sa.String(), nullable=True),
                    sa.Column('name', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('messages',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('type', sa.String(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('service_id', sa.String(), nullable=True),
                    sa.Column('internal_id', sa.Integer(), nullable=True),
                    sa.Column('date', sa.DateTime(), nullable=True),
                    sa.Column('state', sa.Enum('TRANSFERRED', 'PENDING', name='messagestate'), nullable=False),
                    sa.Column('text', sa.String(), nullable=True),
                    sa.Column('buttons', TextJson(), nullable=True),
                    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('sessions',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('service_id', sa.String(), nullable=False),
                    sa.Column('state', sa.Enum('OPEN', 'CLOSE', name='sessionstate'), nullable=False),
                    sa.Column('open_time', sa.DateTime(), nullable=False),
                    sa.Column('close_time', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sessions')
    op.drop_table('messages')
    op.drop_table('users')
    op.drop_table('settings')
    op.drop_table('services')
    # ### end Alembic commands ###
